kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hostpath
  annotations:
    volume.beta.kubernetes.io/storage-class: "k8s-isilon"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
